package com.example.crud

object AppConstant {
    const val TOKEN_JWT = "bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczpcL1wvaHNvcHJvc3BleC5jb21cL2FwaVwvbG9naW5BcGkiLCJpYXQiOjE2NTAxNjI3MDksImV4cCI6MTY2NTcxNDcwOSwibmJmIjoxNjUwMTYyNzA5LCJqdGkiOiJqRlZMZVNZQjN1WjU2dGFIIiwic3ViIjoxMjUsInBydiI6Ijg3ZTBhZjFlZjlmZDE1ODEyZmRlYzk3MTUzYTE0ZTBiMDQ3NTQ2YWEifQ.BxStcPXRr8V3pwdUWwHJJmAD-NrW5NK42OVSrUlW198"
    const val ITEM_KEY = "item_key"
}